groups: []

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: version
  type: semver
  source:
    initial_version: 0.0.1
    driver: git
    uri: git@github.com:pivotalservices/magnet.git
    branch: version
    file: version

- name: pr
  type: pull-request
  source:
    repo: pivotalservices/magnet
    access_token: {{github-access-token}}
    private_key: {{git-private-key}}

- name: master
  type: git
  source:
    branch: master
    private_key: {{git-private-key}}
    uri: git@github.com:pivotalservices/magnet.git

- name: release
  type: git
  source:
    branch: master
    tag_filter: v*.*.[^\\-]
    private_key: {{git-private-key}}
    uri: git@github.com:pivotalservices/magnet.git

- name: prerelease
  type: git
  source:
    branch: master
    tag_filter: v*.*.*-pre*
    private_key: {{git-private-key}}
    uri: git@github.com:pivotalservices/magnet.git

- name: gh-release
  type: github-release
  source:
    user: pivotalservices
    repository: magnet
    access_token: {{github-access-token}}

jobs:
- name: unit
  plan:
  - get: magnet
    resource: master
    trigger: true
  - task: unit
    file: magnet/ci/unit.yml

- name: pr-unit
  plan:
  - get: magnet
    resource: pr
    trigger: true
  - put: pr
    params:
      path: magnet
      status: pending
  - task: unit
    file: magnet/ci/unit.yml
    on_success:
      put: pr
      params:
        path: magnet
        status: success
    on_failure:
      put: pr
      params:
        path: magnet
        status: failure

- name: stage
  plan:
  - get: magnet
    resource: prerelease
    trigger: true
  - task: unit
    file: magnet/ci/unit.yml
  - task: stage
    file: magnet/ci/stage.yml
    on_success:
      put: gh-release
      params:
        name: magnet-bits/tag
        tag: magnet-bits/tag
        globs:
        - magnet-bits/release/*
